# Generated by Django 4.2.7 on 2023-11-25 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('created', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('due_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('related_url', models.URLField(blank=True)),
                ('color', models.CharField(blank=True, max_length=10)),
                ('repeat_period', models.CharField(blank=True, max_length=20)),
                ('viewed', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todos.todo')),
            ],
        ),
    ]
